/*
  This script scans the 'Download' folder (a sibling directory to the 'Games' folder)
  and creates a list of all .nll files found.
  
  The script assumes it is run from the 'Game Stash' directory.
  
  Execution: node build_nll_list.js
*/

const fs = require('fs');
const path = require('path');

// Define the directory containing the .nll files (it's in the same folder as this script)
const nllDir = path.join(__dirname, 'Download');
const nllList = [];

console.log('Scanning for .nll files in:', nllDir);

try {
    // Read all contents of the directory for debugging purposes
    const allContents = fs.readdirSync(nllDir, { withFileTypes: true });

    console.log('\n--- DEBUG: Directory Contents Found ---');
    if (allContents.length === 0) {
        console.log('--- FAILED: Directory is empty or inaccessible. ---');
    } else {
        allContents.forEach(dirent => {
            console.log(`- Item: ${dirent.name}, Type: ${dirent.isDirectory() ? 'Directory' : 'File'}`);
        });
    }
    console.log('----------------------------------------\n');

    // Filter for only files that end in .nll
    const nllFiles = allContents
        .filter(dirent => dirent.isFile() && path.extname(dirent.name).toLowerCase() === '.nll')
        .map(dirent => dirent.name);

    // Add each file to the list
    for (const fileName of nllFiles) {
        // The path for the browser is relative to index.html (i.e., Download/filename.nll)
        const nllPath = path.join('Download', fileName); 

        nllList.push({
            name: fileName, 
            path: nllPath.replace(/\\/g, '/') 
        });
        console.log(`- Found .nll file: ${fileName}`);
    }

    // Write the nlllist.js file into the current directory (alongside index.html)
    const fileContent = `
// THIS FILE IS AUTO-GENERATED!
// Do not edit this file directly.
// Run 'node build_nll_list.js' to update it.

const allNLLs = ${JSON.stringify(nllList, null, 2)};
`;

    fs.writeFileSync(path.join(__dirname, 'nlllist.js'), fileContent);

    console.log(`\nSuccess! Created nlllist.js with ${nllList.length} files.`);
    console.log("Remember to commit this file before pushing to GitHub.");

} catch (err) {
    console.error('\n--- FATAL ERROR ---');
    console.error(`Could not scan the 'Download' folder. The 'Download' folder was not found.`);
    console.error(`Detailed Error: ${err.message}`);
}
