/*
  This is the final configuration for the Node.js script.
  It assumes the script is inside 'Game Stash/' and is looking for the 
  'Games/' folder inside 'Game Stash/'.
*/

const fs = require('fs');
const path = require('path');

// Set the path to the 'Games' folder, which is in the same directory as this script.
const gamesDir = path.join(__dirname, 'Games');
const gameList = [];

console.log('Scanning for HTML files in:', gamesDir);

try {
    // Read ALL contents of the directory for debugging purposes
    const allContents = fs.readdirSync(gamesDir, { withFileTypes: true });

    console.log('\n--- DEBUG: Directory Contents Found ---');
    if (allContents.length === 0) {
        console.log('--- FAILED: Directory is empty or inaccessible. ---');
    } else {
        allContents.forEach(dirent => {
            console.log(`- Item: ${dirent.name}, Type: ${dirent.isDirectory() ? 'Directory' : 'File'}`);
        });
    }
    console.log('----------------------------------------\n');

    // Filter for only files that end in .html
    const gameFiles = allContents
        .filter(dirent => dirent.isFile() && path.extname(dirent.name).toLowerCase() === '.html')
        .map(dirent => dirent.name);

    // Add each file to the list
    for (const fileName of gameFiles) {
        // The link path for the browser is relative to index.html (i.e., Games/game.html)
        const gamePath = path.join('Games', fileName); 

        gameList.push({
            name: fileName, 
            path: gamePath.replace(/\\/g, '/') 
        });
        console.log(`- Found game file: ${fileName}`);
    }

    // Write the gamelist.js file into the current directory (alongside index.html)
    const fileContent = `
// THIS FILE IS AUTO-GENERATED!
// Do not edit this file directly.
// Run this script from the 'Game Stash' folder to update it.

const allGames = ${JSON.stringify(gameList, null, 2)};
`;

    fs.writeFileSync(path.join(__dirname, 'gamelist.js'), fileContent);

    console.log(`\nSuccess! Created gamelist.js with ${gameList.length} games.`);
    console.log("Remember to commit this file before pushing to GitHub.");

} catch (err) {
    console.error('\n--- FATAL ERROR ---');
    console.error(`Could not scan the 'Games' folder. The 'Games' folder was not found.`);
    console.error(`Detailed Error: ${err.message}`);
}