
// THIS FILE IS AUTO-GENERATED!
// Do not edit this file directly.
// Run 'node build_nll_list.js' to update it.

const allNLLs = [
  {
    "name": "DeltaRune.nll",
    "path": "Download/DeltaRune.nll"
  },
  {
    "name": "DesktopGoose v0.31.nll",
    "path": "Download/DesktopGoose v0.31.nll"
  },
  {
    "name": "Edenwound.nll",
    "path": "Download/Edenwound.nll"
  },
  {
    "name": "Friday Night Funkin'.nll",
    "path": "Download/Friday Night Funkin'.nll"
  },
  {
    "name": "Geometry Dash.nll",
    "path": "Download/Geometry Dash.nll"
  },
  {
    "name": "George and the Printer.nll",
    "path": "Download/George and the Printer.nll"
  },
  {
    "name": "Give Up the Ghost; a puzzle checklist.nll",
    "path": "Download/Give Up the Ghost; a puzzle checklist.nll"
  },
  {
    "name": "Hardware Tycoon.nll",
    "path": "Download/Hardware Tycoon.nll"
  },
  {
    "name": "Hex of Steel; an RTS game set in WW2.nll",
    "path": "Download/Hex of Steel; an RTS game set in WW2.nll"
  },
  {
    "name": "Little Chef.nll",
    "path": "Download/Little Chef.nll"
  },
  {
    "name": "Minato; Minesweeper but different.nll",
    "path": "Download/Minato; Minesweeper but different.nll"
  },
  {
    "name": "Pumpkin Cafe Coffee Game Jam.nll",
    "path": "Download/Pumpkin Cafe Coffee Game Jam.nll"
  },
  {
    "name": "Scale the Depths Fishing.nll",
    "path": "Download/Scale the Depths Fishing.nll"
  },
  {
    "name": "Undertale.nll",
    "path": "Download/Undertale.nll"
  }
];
